# Deliverable 2. Create a Customer Travel Destinations Map.
----
1. Create a folder called `Vacation_Search` to save all the files related with this deliverable.

2. Download the `Vacation_Search_starter_code.ipynb` Jupyter notebook,save it into your `Vacation_Search folder`, and rename it as `Vacation_Search.ipynb`.

3. In the `Vacation_Search.ipynb` file, ensure that the dependencies and the Google API key is imported correctly.

4. From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame named `city_data_df`.

5. Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

6. Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected. Name the DataFrame as `preferred_cities_df`.

7. Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

8. Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

9. Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

10. Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

11. Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

12. Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

13. Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

14. Review the formatting template provided that you'll use to add an information box to each marker in the map. In the pop-up for each city you'll add:

    1. The city name.

    2. The country code.

    3. The weather description and maximum temperature for the city.

15. Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

16. Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

17. Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

18. Take a screenshot of your map and save it to the `Vacation_Search` folder as `WeatherPy_vacation_map.png`.
---

## Ensure that the dependencies and the Google API key is imported correctly.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import Google API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

## From the `Weather_Database` folder you created in the "Deliverable 1," import the `WeatherPy_Database.csv` file as a Pandas DataFrame.

In [3]:
# Set the file path to import the WeatherPy_database.csv file
file_path = "../Weather_Database/WeatherPy_database.csv"

# Load the CSV file into a Pandas DataFrame
city_data_df = pd.read_csv(file_path)

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,0,East London,-33.0153,27.9116,64.33,85,0,15.30,ZA,2022-10-27 01:36:37,clear sky
1,1,Grand-Santi,4.2500,-54.3833,73.08,96,53,2.55,GF,2022-10-27 01:36:37,light rain
2,2,Colares,38.7992,-9.4469,70.75,97,100,15.01,PT,2022-10-27 01:36:38,overcast clouds
3,3,Blind River,46.1834,-82.9582,41.11,65,100,14.27,CA,2022-10-27 01:36:38,overcast clouds
4,4,Ushuaia,-54.8000,-68.3000,47.86,57,100,11.50,AR,2022-10-27 01:36:38,light intensity drizzle

## Write two input statements that prompt the user to enter their minimum and maximum temperature criteria for their vacation.

In [4]:
# Prompt the user to enter the minimum temperature criteria
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

# Prompt the user to enter the maximum temperature criteria
max_temp = float(input("What is the maxiumum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maxiumum temperature you would like for your trip? 90

## Create a new Pandas DataFrame by using the `loc` Pandas method to filter the `city_data_df` DataFrame for temperature criteria  collected.

In [5]:
# Filter the city_data_df DataFrame to find the cities that fit the criteria using the loc Pandas function
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
                                    
# Display sample data
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
5,5,Felipe Carrillo Puerto,19.5833,-88.0500,76.95,79,99,2.62,MX,2022-10-27 01:36:39,overcast clouds
15,15,Olinda,-8.0089,-34.8553,80.33,69,40,5.75,BR,2022-10-27 01:36:42,scattered clouds
16,16,Rodrigues Alves,-7.7380,-72.6509,76.59,86,36,2.15,BR,2022-10-27 01:36:42,scattered clouds
17,17,Baiao,-2.7906,-49.6717,75.54,85,100,0.78,BR,2022-10-27 01:36:42,overcast clouds
25,25,Cayenne,4.9333,-52.3333,77.04,94,100,2.30,GF,2022-10-27 01:36:45,overcast clouds
27,27,Georgetown,5.4112,100.3354,83.23,84,20,3.44,MY,2022-10-27 01:32:54,few clouds
28,28,Quelimane,-17.8786,36.8883,76.95,83,0,9.22,MZ,2022-10-27 01:36:46,clear sky
29,29,Puerto Colombia,10.9878,-74.9547,80.69,80,29,11.07,CO,2022-10-27 01:36:46,scattered clouds
32,32,Hithadhoo,-0.6000,73.0833,82.20,75,35,7.67,MV,2022-10-27 01:36:47,scattered clouds
45,45,Libreville,0.3925,9.4537,80.62,89,75,3.44,GA,2022-10-27 01:37:51,thunderstorm

## Create a new Pandas DataFrame named `clean_travel_cities` by using the Pandas `dropna` function on the `preferred_cities_df` to drop any empty rows.

In [6]:
# Drop any empty rows in the preferred_cities_df DataFrame and create a new DataFrame.
clean_travel_cities = preferred_cities_df.dropna()
# Display sample data
clean_travel_cities

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
5,5,Felipe Carrillo Puerto,19.5833,-88.0500,76.95,79,99,2.62,MX,2022-10-27 01:36:39,overcast clouds
15,15,Olinda,-8.0089,-34.8553,80.33,69,40,5.75,BR,2022-10-27 01:36:42,scattered clouds
16,16,Rodrigues Alves,-7.7380,-72.6509,76.59,86,36,2.15,BR,2022-10-27 01:36:42,scattered clouds
17,17,Baiao,-2.7906,-49.6717,75.54,85,100,0.78,BR,2022-10-27 01:36:42,overcast clouds
25,25,Cayenne,4.9333,-52.3333,77.04,94,100,2.30,GF,2022-10-27 01:36:45,overcast clouds
...,...,...,...,...,...,...,...,...,...,...,...
681,681,Kidal,18.4411,1.4078,75.06,18,6,15.46,ML,2022-10-27 01:54:23,clear sky
682,682,Puerto Carreno,6.1890,-67.4859,79.90,79,100,4.81,CO,2022-10-27 01:54:23,overcast clouds
683,683,Santo Domingo,18.5001,-69.9886,76.93,91,40,0.00,DO,2022-10-27 01:50:50,scattered clouds
685,685,Atar,20.5169,-13.0499,80.29,12,7,6.71,MR,2022-10-27 01:54:24,clear sky
686,686,Korhogo,9.4500,-5.6333,75.72,76,64,1.57,CI,2022-10-27 01:55:24,broken clouds

## Use the `copy` Pandas function to create a new DataFrame, called `hotel_df`, by copying the following columns from the `clean_travel_cities` DataFrame: "City", "Country", "Max Temp", "Current Description", "Lat", "Lng".

In [7]:
# Create DataFrame called hotel_df by copying some columns from the clean_travel_cities DataFrame.
hotel_df = clean_travel_cities[['City', 'Country', 'Max Temp', "Current Description", "Lat", "Lng"]].copy()

# Display sample data
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng
5,Felipe Carrillo Puerto,MX,76.95,overcast clouds,19.5833,-88.0500
15,Olinda,BR,80.33,scattered clouds,-8.0089,-34.8553
16,Rodrigues Alves,BR,76.59,scattered clouds,-7.7380,-72.6509
17,Baiao,BR,75.54,overcast clouds,-2.7906,-49.6717
25,Cayenne,GF,77.04,overcast clouds,4.9333,-52.3333

## Add a new empty column named `Hotel Name` to the `hotel_df` DataFrame.

In [8]:
# Add a new empty column, "Hotel Name", to the hotel_df DataFrame
hotel_df['Hotel Name'] = ''

# Display sample data
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Felipe Carrillo Puerto,MX,76.95,overcast clouds,19.5833,-88.0500,
15,Olinda,BR,80.33,scattered clouds,-8.0089,-34.8553,
16,Rodrigues Alves,BR,76.59,scattered clouds,-7.7380,-72.6509,
17,Baiao,BR,75.54,overcast clouds,-2.7906,-49.6717,
25,Cayenne,GF,77.04,overcast clouds,4.9333,-52.3333,

## Review the hotel search parameters provided. These parameters are the same we used in this module; you'll use them to search for a hotel for each city.

In [9]:
# Review the parameters to search for a hotel
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

## Use a for loop to iterate through the `hotel_df` DataFrame, retrieve the latitude and longitude of each city to find the nearest hotel based on the search parameters provided, then add the hotel name to the `hotel_df` DataFrame. If a hotel isn't found, skip to the next city.

In [10]:
# Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # Fetch latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude as parameters to the params dictionary
    params["location"] = f"{lat},{lng}"
    
    # Set up the base URL for the Google Directions API to get JSON data
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make an API request and retrieve the JSON data from the hotel search
    hotels = requests.get(base_url, params=params).json()
    
    # Get the first hotel from the results and store the name, if a hotel isn't found skip the city
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
# Display sample data
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Felipe Carrillo Puerto,MX,76.95,overcast clouds,19.5833,-88.0500,Hotel La Ceiba
15,Olinda,BR,80.33,scattered clouds,-8.0089,-34.8553,Flat Quatro Rodas Olinda
16,Rodrigues Alves,BR,76.59,scattered clouds,-7.7380,-72.6509,Pousada Aconchego
17,Baiao,BR,75.54,overcast clouds,-2.7906,-49.6717,Município de Baião
25,Cayenne,GF,77.04,overcast clouds,4.9333,-52.3333,Hôtel Le Dronmi

## Drop any rows in the `hotel_df` DataFrame where a hotel name is not found and store the resulting data into a new DataFrame named `clean_hotel_df`.

In [12]:
# Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(subset=['Hotel Name'], how='any')

# Display sample data

clean_hotel_df = clean_hotel_df[clean_hotel_df['Hotel Name'].astype(bool)]
clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
5,Felipe Carrillo Puerto,MX,76.95,overcast clouds,19.5833,-88.0500,Hotel La Ceiba
15,Olinda,BR,80.33,scattered clouds,-8.0089,-34.8553,Flat Quatro Rodas Olinda
16,Rodrigues Alves,BR,76.59,scattered clouds,-7.7380,-72.6509,Pousada Aconchego
17,Baiao,BR,75.54,overcast clouds,-2.7906,-49.6717,Município de Baião
25,Cayenne,GF,77.04,overcast clouds,4.9333,-52.3333,Hôtel Le Dronmi

**Note:** If the resulting DataFrame is empty, uncomment the following code to load sample data into the `clean_hotel_df`.

In [13]:
# In case of an empty DataFrame, load the sample data provided
# clean_hotel_df = pd.read_csv("WeatherPy_vacation-backup.csv")
# clean_hotel_df.head(10)

## Create an CSV file to store the `clean_hotel_df` DataFrame as `WeatherPy_vacation.csv` in the Vacation_Search folder.

In [14]:
# Set the file name.
output_data_file = 'WeathterPy_vacation.csv'

# Create a CSV file by using the clean_hotel_df DataFrame
clean_hotel_df.to_csv(output_data_file)

### Review the formatting template provided that you'll use to add an information box to each marker in the map.

In the pop-up for each city you'll add: 

1. The city name

2. The country code

3. The weather description and maximum temperature for the city

In [15]:
# Review the formatting template provided
info_box_template = """


Hotel Name
    {Hotel Name}

City
{City}
Country
{Country}
Current Weather
    {Current Description} and {Max Temp} °F


"""

## Review the provided list comprehension code to retrieve the city data from each row, which will then be added to the formatting template and saved in the `hotel_info` list.

In [16]:
# Get the data from each row in the clean_hotel_df DataFrame, add it to the formatting template, and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# Display sample data
hotel_info[:10]

['\n\n\nHotel Name\n    Hotel La Ceiba\n\nCity\nFelipe Carrillo Puerto\nCountry\nMX\nCurrent Weather\n    overcast clouds and 76.95 °F\n\n\n',
 '\n\n\nHotel Name\n    Flat Quatro Rodas Olinda\n\nCity\nOlinda\nCountry\nBR\nCurrent Weather\n    scattered clouds and 80.33 °F\n\n\n',
 '\n\n\nHotel Name\n    Pousada Aconchego\n\nCity\nRodrigues Alves\nCountry\nBR\nCurrent Weather\n    scattered clouds and 76.59 °F\n\n\n',
 '\n\n\nHotel Name\n    Município de Baião\n\nCity\nBaiao\nCountry\nBR\nCurrent Weather\n    overcast clouds and 75.54 °F\n\n\n',
 '\n\n\nHotel Name\n    Hôtel Le Dronmi\n\nCity\nCayenne\nCountry\nGF\nCurrent Weather\n    overcast clouds and 77.04 °F\n\n\n',
 '\n\n\nHotel Name\n    Cititel Penang\n\nCity\nGeorgetown\nCountry\nMY\nCurrent Weather\n    few clouds and 83.23 °F\n\n\n',
 '\n\n\nHotel Name\n    Hotel Flamingo\n\nCity\nQuelimane\nCountry\nMZ\nCurrent Weather\n    clear sky and 76.95 °F\n\n\n',
 '\n\n\nHotel Name\n    Hotel El Emigrante\n\nCity\nPuerto Colombia\nCountry\nCO\nCurrent Weather\n    scattered clouds and 80.69 °F\n\n\n',
 '\n\n\nHotel Name\n    Scoop Guest House\n\nCity\nHithadhoo\nCountry\nMV\nCurrent Weather\n    scattered clouds and 82.2 °F\n\n\n',
 '\n\n\nHotel Name\n    Hotel Kreg Le Patio\n\nCity\nLibreville\nCountry\nGA\nCurrent Weather\n    thunderstorm and 80.62 °F\n\n\n']

## Use the provided code snippet to retrieve the latitude and longitude from each row and store them in a new DataFrame called `locations`.

In [17]:
# Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

# Display sample data
locations.head(10)

        Lat       Lng
5   19.5833  -88.0500
15  -8.0089  -34.8553
16  -7.7380  -72.6509
17  -2.7906  -49.6717
25   4.9333  -52.3333
27   5.4112  100.3354
28 -17.8786   36.8883
29  10.9878  -74.9547
32  -0.6000   73.0833
45   0.3925    9.4537

## Refactor your previous marker layer map code to create a marker layer map that will have pop-up markers for each city on the map.

In [18]:
# Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)


# Create a figure to add the Google map as a layer
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Display the figure containing the map
fig

Figure(layout=FigureLayout(height='420px'))